version: 2
plugins:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  phpcs:
    enabled: true
  # Add other plugins as needed

exclude_patterns:
  - "**/vendor/**"
  - "**/node_modules/**"
  # Add more exclusion patterns as needed

languages:
  # Specify the languages you want to analyze
  - python
  # Add more languages as needed

config:
  # Add language-specific configuration options here
  python:
    config:
      max_complexity: 10
  
