rules:
  - id: python.langsec.insecure-deserialization
    severity: WARNING
    languages:
      - python
    patterns:
      - pattern: pickle.loads({any_arguments})
    message: "Insecure deserialization detected"
