# Generated by Django 4.2.4 on 2023-08-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cat_image",
            field=models.ImageField(blank=True, upload_to="photo/categories"),
        ),
    ]
