name: Run Bandit

on:
  push:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Bandit
        uses: docker://bandit/bandit:latest
        with:
          args: -r .

