name: Run Bandit

on:
  push:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Bandit
        run: |
          docker run --rm -v $PWD:/code -w /code bandit/bandit:latest bandit -r .
