on:
  push:
    branches:
      - main

jobs:
  all_checks:
    name: All Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install semgrep bandit
          npm install -g codeclimate-test-reporter snyk
          
      - name: Run Semgrep
        run: semgrep -o semgrep-report.html --config=.semgrep.yml .
        continue-on-error: true

      - name: Run Bandit
        run: bandit -r . -f html -o bandit-report.html
        continue-on-error: true

      - name: Run CodeClimate
        run: |
          codeclimate-test-reporter format-coverage -t coverage.py -o codeclimate.json
          codeclimate-test-reporter upload-coverage -i codeclimate.json
        continue-on-error: true

      - name: Generate Synk Report URL
        run: |
          # Generate the Synk report URL and save it to a file
          echo "https://app.snyk.io/org/hymasaranya/project/9b7a5f6e-32f5-4818-a6c1-d95d143662c0" > snyk_report_url.txt

      - name: Upload Snyk Report URL
        uses: actions/upload-artifact@v2
        with:
          name: snyk-report-url
          path: snyk_report_url.txt

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            semgrep-report.html
            bandit-report.html
            codeclimate.json
            snyk-report.json
