name: DevSecOps Workflow

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install semgrep bandit
          npm install -g codeclimate-test-reporter snyk

      - name: Run Semgrep
        run: semgrep -o semgrep-report.html --config=.semgrep.yml .

      - name: Run Bandit
        run: bandit -r . -f json -o bandit-report.json

      - name: Convert Bandit JSON to HTML
        run: bandit -f html -o bandit-report.html -n 1 -x bandit-report.json

      - name: Run CodeClimate
        run: |
          codeclimate-test-reporter format-coverage -t coverage.py -o codeclimate.html
          codeclimate-test-reporter upload-coverage -i codeclimate.html

      - name: Run Snyk
        run: snyk test --all-projects --json > snyk-report.json

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            semgrep-report.html
            bandit-report.html
            codeclimate.html
            snyk-report.json

  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run SonarCloud
        run: |
          sonar-scanner \
            -Dsonar.organization=hymasaranya \
            -Dsonar.projectKey=hymasaranya \
            -Dsonar.sources=.

      - name: Upload SonarCloud Report
        uses: actions/upload-artifact@v2
        with:
          name: sonarcloud-report
          path: .scannerwork/report-task.txt
