on:
  push:
    branches:
      - main

jobs:
  all_checks:
    name: All Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install semgrep bandit
          npm install -g codeclimate-test-reporter snyk

      - name: Run Semgrep
        run: semgrep --config=.semgrep.yml .
        continue-on-error: true

      - name: Run Bandit and Generate HTML Report
        run: |
          bandit -r . -f html -o bandit-report.html
        continue-on-error: true

      - name: Run CodeClimate
        run: |
          codeclimate-test-reporter format-coverage -t coverage.py -o codeclimate-report.html
          codeclimate-test-reporter upload-coverage -i codeclimate-report.html
        continue-on-error: true

      - name: Fetch Data from Synk, SonarCloud
        run: |
          synk_data=$(curl -s https://app.snyk.io/org/hymasaranya/project/9b7a5f6e-32f5-4818-a6c1-d95d143662c0)
          sonarcloud_data=$(curl -s https://sonarcloud.io/projects)

          echo "$synk_data" > synk-report.html
          echo "$sonarcloud_data" > sonarcloud-report.html

      - name: Print Bandit Report
        run: cat bandit-report.html

      - name: Print CodeClimate Report
        run: cat codeclimate-report.html

      - name: Print Synk Report
        run: cat synk-report.html

      - name: Print SonarCloud Report
        run: cat sonarcloud-report.html

      - name: Upload Reports as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            bandit-report.html
            codeclimate-report.html
            synk-report.html
            sonarcloud-report.html
