name: DevSecOps Workflow

on:
  push:
    branches:
      - main

jobs:
  all_checks:
    name: All Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install semgrep bandit
          npm install -g codeclimate-test-reporter snyk

      - name: Run Semgrep
        run: semgrep -o semgrep-report.html --config=.semgrep.yml .
        continue-on-error: true

      - name: Run Bandit
        run: bandit -r . -f html -o bandit-report.html
        continue-on-error: true

      - name: Run CodeClimate
        run: |
          codeclimate-test-reporter format-coverage -t coverage.py -o codeclimate.json
          codeclimate-test-reporter upload-coverage -i codeclimate.json
        continue-on-error: true

      - name: Run Snyk
        run: snyk test --all-projects --all-sub-projects --json > snyk-report.json
        continue-on-error: true

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: |
            semgrep-report.html
            bandit-report.html
            codeclimate.json
            snyk-report.json
