on:
  push:
    branches:
      - main

jobs:
  all_checks:
    name: All Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install semgrep bandit
          npm install -g codeclimate-test-reporter snyk

      - name: Run Semgrep
        run: semgrep --config=.semgrep.yml .
        continue-on-error: true

      - name: Run Bandit
        run: bandit -r .
        continue-on-error: true

      - name: Fetch Data from Synk, SonarCloud, and CodeClimate
        run: |
          synk_data=$(curl -s https://app.snyk.io/org/hymasaranya/project/9b7a5f6e-32f5-4818-a6c1-d95d143662c0)
          sonarcloud_data=$(curl -s https://sonarcloud.io/projects)
          codeclimate_data=$(curl -s https://codeclimate.com/github/HymaSaranya/DevSecOps_Thesis)

          echo "$synk_data" > synk-report.txt
          echo "$sonarcloud_data" > sonarcloud-report.txt
          echo "$codeclimate_data" > codeclimate-report.txt

      - name: Consolidate Reports
        run: |
          cat synk-report.txt sonarcloud-report.txt codeclimate-report.txt > consolidated-reports.txt
        continue-on-error: true

      - name: Print Bandit Report
        run: cat bandit-report.txt

      - name: Print Semgrep Results
        run: semgrep --config=.semgrep.yml . --json | jq
        continue-on-error: true

      - name: Print Consolidated Reports
        run: cat consolidated-reports.txt

      - name: Upload Consolidated Reports
        uses: actions/upload-artifact@v2
        with:
          name: consolidated-reports
          path: consolidated-reports.txt
