name: DevSecOps Workflow

on:
  push:
    branches:
      - main

jobs:
  combine_reports:
    name: Combine Reports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Combine Reports
        run: |
          cat semgrep-report.txt >> combined-report.txt
          cat bandit-report.txt >> combined-report.txt
          cat codeclimate-report.txt >> combined-report.txt
          cat snyk-report.txt >> combined-report.txt
          echo "SonarCloud Report: $SONARQUBE_PROJECT_URL/dashboard?id=$GITHUB_REPOSITORY" >> combined-report.txt

      - name: Upload Combined Report
        uses: actions/upload-artifact@v2
        with:
          name: combined-report
          path: combined-report.txt
