name: DevSecOps Workflow

on:
  push:
    branches:
      - main

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install semgrep bandit
          npm install -g codeclimate-test-reporter snyk

      - name: Run Semgrep
        run: semgrep -o semgrep-report.txt --config=.semgrep.yml .

      - name: Run Bandit
        run: bandit -r . -f custom -o bandit-report.txt || true

      - name: Run CodeClimate
        run: |
          codeclimate-test-reporter format-coverage -t coverage.py -o codeclimate.txt
        env:
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}

      - name: Run Snyk
        run: snyk test --all-projects --json > snyk-report.txt

      - name: Generate SonarCloud Report Link
        run: echo "SonarCloud Report: $SONARQUBE_PROJECT_URL/dashboard?id=$GITHUB_REPOSITORY"

      - name: Combine Reports
        run: |
          cat semgrep-report.txt >> combined-report.txt
          cat bandit-report.txt >> combined-report.txt
          cat codeclimate.txt >> combined-report.txt
          cat snyk-report.txt >> combined-report.txt

      - name: Upload Combined Report
        uses: actions/upload-artifact@v2
        with:
          name: combined-report
          path: combined-report.txt
